### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by bscully27** [EelcoHoogendoorn/Numpy_arraysetops_EP#10]
1) Are there any speed performance tests vs Pandas vs Modin vs PandaPy?
2) I'm getting this error with npi.group_by().reduce().  The example uses sum but i'd eventually like to supply a numpy compatible function.  I'm probably mis-using reduce..
```
Traceback (most recent call last):
  File "C:\intelpython3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-115-626f4910da53>", line 1, in <module>
    **sums = npi.group_by(matrix[:, :3]).reduce(matrix[:, -1], np.sum)**
  File "C:\intelpython3\lib\site-packages\numpy_indexed\grouping.py", line 213, in reduce
    return operator.reduceat(values, self.index.start, axis=axis, dtype=dtype)
AttributeError: 'function' object has no attribute 'reduceat'
```
3) With obj = npi.group_by(matrix[:, :3]), how can I get the order of the indexers?

Thanks!

**Comment by EelcoHoogendoorn** [comment]
1: This package isnt overly oncerned with speed; while all operations are vectorized, thus not slow, its quite possible you may find an implementation elsewhere that is a few times faster.

2: this is meant to be used with numpy [ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html); not generic callables.

3: i dont know what that means exactly.

**Comment by bscully27** [comment]
Got it, thanks for the quick response.
