### ISSUE TITLE
TypeError: invalid type promotion when using data with 3 variables

### ISSUE THREAD

**Issue by seralouk** [EelcoHoogendoorn/Numpy_arraysetops_EP#11]
I have 2 matrices with shapes `(159459, 3)` and `(5022, 3)` and I followed this answer by the author (https://stackoverflow.com/a/39587388/5025009) of the module in order to get the indices.

I get: 

`TypeError: invalid type promotion`

Using input matrices with 2 variables e.g. `(159459, 2)` and `(5022, 2)`, it works fine.

**Comment by Korijn** [comment]
Can you share your a bit of code that reproduces the problem, and explain what you are trying to compute?

**Comment by seralouk** [comment]
> Can you share your a bit of code that reproduces the problem, and explain what you are trying to compute?

Just solved my issue. I had a mismatch in the dtype of the 2 numpy arrays. After converting both into dtype='float' you module does an excellent work. Thanks ! SUPER fast!
