### ISSUE TITLE
npi.indexes does not seem to work as expected

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [EelcoHoogendoorn/Numpy_arraysetops_EP#19]
by the doc, it should be that `this[indexes] == that`, however:
```
items = np.array([[1,2,3], [2,3,4], [4,5,6]])
to_search = np.array([[1,2,4], [2,3,4]])
npi.indices(items, to_search, missing="ignore")
```
returns `[1,1]`

Any explanation?

Edit:  
same changing the axis... I would expect to treat each subvector as "item to search from/into", thus in this case there should be just `1` returned... however, even stranger, using `to_search = np.array([[1,2,4])` returns something.. which does not makes sense, as there are no element that matches it

**Comment by EelcoHoogendoorn** [comment]
From the docstring;
```        if `missing` is 'ignore', all elements of `that` are assumed to be present in `this`,
        and output is undefined otherwise
```
`[1,2,4]` isnt to be found in the zeroth axis of `items`; hence you get undefined output.

Maybe you meant to pass in an axis=1 arg?

**Comment by AlbertoSinigaglia** [comment]
> From the docstring;
> 
> > if `missing` is 'ignore', all elements of `that` are assumed to be present in `this`, and output is undefined otherwise
> 
> 
> 
> `[1,2,4]` isnt to be found in the zeroth axis of `items`; hence you get undefined output.
> 
> 
> 
> Maybe you meant to pass in an axis=1 arg?

 
What's the point of having a undefined behavior in a case where there is a obvious intuitive behavior?... wouldn't it be so nice to remove the "undefineteness"?

**Comment by EelcoHoogendoorn** [comment]
Whats `obvious intuitive behavior` do you have in mind, for a nonexisting lookup, whos error message you chose to suppress?
