### ISSUE TITLE
Empty list in npi.indices causes deprecation error in latest version of numpy

### ISSUE THREAD

**Issue by MatteoBouvier** [EelcoHoogendoorn/Numpy_arraysetops_EP#20]
Hi, I have been using numpy-indexed for a while now but recently encountered an incompatibility with the latest version of numpy (1.24) :
When calling `numpy_indexed.indices(a, b)` where b is an empty list, this raises a deprecation error because of line 51 in index.py : `self.flag = np.empty(0, np.bool)` (np.bool is now deprecated and should be replaced by `np.bool_` or simply `bool`).

As an example, this reproduces the issue : 
```python
npi.indices([0, 1, 2], [])
```

Thanks for the great work !

**Comment by EelcoHoogendoorn** [comment]
Should be fixed in the latest pypi release pf 0.3.7
