### ISSUE TITLE
conda-forge and 0.3.7

### ISSUE THREAD

**Issue by Thomas-Z** [EelcoHoogendoorn/Numpy_arraysetops_EP#23]
Hello,

Just a question, not really an issue!

Do you intend to publish the latest numpy-indexed version [to conda-forge](https://anaconda.org/conda-forge/numpy-indexed/files)?

Regards and thank you for this library,
Thomas

**Comment by EelcoHoogendoorn** [comment]
Sort of, yes. I made a half-hearted attempt, but conda-forge has grown to be so complex over the years I was intimidated into not diving back into it. If you consider yourself versed in things conda forge im happy to add you as a maintainer there!

**Comment by Thomas-Z** [comment]
Never done it but I can give it a try.

**Comment by EelcoHoogendoorn** [comment]
Looks like I dont need to add you; you just fork and make a PR I think. For a project without complex build dependencies like this it should be pretty easy given the [tagged](https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP/tree/0.3.7) release.

**Comment by Thomas-Z** [comment]
Just [have to wait now.](https://github.com/conda-forge/numpy-indexed-feedstock/pull/8)

**Comment by Thomas-Z** [comment]
[Package available on conda-forge](https://anaconda.org/conda-forge/numpy-indexed/files), I think we can close this.

Thanks for maintaining this library (and for allowing me to understand the conda-forge submission process).

**Comment by EelcoHoogendoorn** [comment]
Thank you for contributing!
