### ISSUE TITLE
Release 0.3.5 to pypi

### ISSUE THREAD

**Issue by Korijn** [EelcoHoogendoorn/Numpy_arraysetops_EP#5]
I don't have permission to upload the new universal wheel to pypi. Can @EelcoHoogendoorn perhaps give me the rights to do it? Otherwise I can provide you with a build over email... alternatively, here is how to build:

First install pipenv with `pip install pipenv --upgrade`. Then setup your virtualenv with `pipenv install --dev`. Finally, build your wheel with `pipenv run python setup.py bdist_wheel`. It should be in the `dist` folder, ready to be uploaded to pypi.

**Comment by EelcoHoogendoorn** [comment]
Sure, I can add you as a maintainer to the pypi page; what is your pypi user name?

**Comment by Korijn** [comment]
https://pypi.org/user/Korijn/

Thanks!

**Comment by EelcoHoogendoorn** [comment]
You should be added now!

**Comment by Korijn** [comment]
v0.3.5 is available on PyPI and also on conda-forge now.
